---
title: "Test data wrangling"
author: "Stace Beaulieu"
date: "October 22, 2018"
output: html_document
---

```{r}
library(tidyverse) # install.packages("tidyverse")
```

```{r}
gapminder <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder.csv')
```

```{r}
install.packages("skimr")
skimr::skim(gapminder)
```

```{r}
# filter by rows
gap_Cambodia <- filter(gapminder, country == "Cambodia")
gap_Cambodia2 <- select(gap_Cambodia, -continent, -lifeExp)

```

The pipe operator (which does not look like a pipe symbol!) will change your life

```{r}
# this:
gapminder %>% head()
# is equivalent to
head(gapminder)
# now go back to Cambodia example
gap_Cambodia <- gapminder %>%
  filter(country == "Cambodia") %>%
  select(-continent, -lifeExp)
gap_Cambodia
```

```{r}
gapminder %>%
  select(-continent, -lifeExp) %>% # not super necessary but to simplify
  filter(country == "Egypt") %>%
  mutate(gdp = pop * gdpPercap) %>%
  mutate(max_gdp = max(gdp))

## you can also create multiple variables within the same mutate(), and line them up so they are easier to read:
gapminder %>%
  select(-continent, -lifeExp) %>% # not super necessary but to simplify
  filter(country == "Vietnam") %>% 
  mutate(gdp     = pop * gdpPercap,
         max_gdp = max(gdp))

```

```{r}
gapminder %>%
  group_by(country) %>%
  mutate(gdp     = pop * gdpPercap,
         max_gdp = max(gdp)) %>%
  ungroup() %>% 
  tail(30)

# with summarize() or summarise()
gapminder %>%
  group_by(country) %>%
  mutate(gdp = pop * gdpPercap) %>%
  summarize(max_gdp = max(gdp)) %>%
  ungroup() %>%
  arrange(desc(max_gdp))
  tail(30)
  
```

```{r}
## read in the data. (same URL as yesterday, with co2.csv instead of gapminder.csv)
co2 <- read_csv("https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/co2.csv")

## explore
co2 %>% head()
co2 %>% dim() # 12

## create new variable that is only 2007 data
gap_2007 <- gapminder %>%
  filter(year == 2007) 
gap_2007 %>% dim() # 142  

# left join in which we want to prioritize gapminder countries
lj <- left_join(gap_2007, co2, by = "country")
lj2 <- left_join(co2, gap_2007, by = "country")

# right join in which we prioritize the co2 data
rj <- right_join(gap_2007, co2, by = "country")
  

```

```{r}
## wide format
gap_wide <- readr::read_csv('https://raw.githubusercontent.com/OHI-Science/data-science-training/master/data/gapminder_wide.csv')

?gather
gap_long <- gap_wide %>% 
  gather(key = obstype_year,
         value = obs_values,
         -continent, -country) %>% 
  separate(col = obstype_year,
           into = c("obs_type", "year"),
           sep = "_",
           convert = TRUE)
head(gap_long)

```

```{r}
canada_df <- gap_long %>%
  filter(obs_type == "lifeExp",
         country == "Canada")

ggplot(canada_df, aes(x = year, y = obs_values)) +
  geom_line()

Americas_df <- gap_long %>%
  filter(obs_type == "lifeExp",
         continent == "Americas")

ggplot(Americas_df, aes(x = year, y = obs_values, color = country)) +
  geom_line()

```
Using gap_long, calculate and plot the the mean life expectancy for each continent over time from 1982 to 2007. Give your plot a title and assign x and y labels. Hint: use the dplyr::group_by() and dplyr::summarize() functions.

```{r}
cont_lifeExp_mean <- gap_long %>%
  filter(obs_type == "lifeExp") %>% 
  group_by(continent, year) %>%
  summarize(lifeExp_mean = mean(obs_values))%>%
  ungroup() %>% 
  ggplot(aes(x = year, y = lifeExp_mean, color = continent)) +
  geom_line()
cont_lifeExp_mean
  
```


